"""
Invoice service — Phase 9.

Generates a PDF invoice using fpdf2 (pure Python, no system libs needed).

Flow:
    1. Query Business + Sale + Customer + SerialNumbers
    2. Build the PDF with fpdf2
    3. Save to settings.PDF_DIR / "invoice_{sale_number}.pdf"
    4. Return the Path to the PDF

The caller (endpoint) wraps the result in a FileResponse.
"""

from pathlib import Path
from datetime import datetime, timezone
from sqlalchemy.orm import Session
from fastapi import HTTPException
from fpdf import FPDF

from app.core.config import settings
from app.models.sale import Sale
from app.models.business import Business
from app.models.serial import SerialNumber
from app.services.sale_service import get_sale


# ── Currency symbol map ───────────────────────────────────────────────────────

CURRENCY_SYMBOLS: dict[str, str] = {
    "BDT": "BDT",   # fpdf2 core fonts don't support Bengali Unicode glyph
    "USD": "USD",
    "EUR": "EUR",
    "GBP": "GBP",
    "INR": "INR",
}


def _fmt(value) -> str:
    try:
        return f"{float(value):,.2f}"
    except (TypeError, ValueError):
        return "0.00"


class InvoicePDF(FPDF):
    def __init__(self, business_name: str, currency: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.business_name = business_name
        self.currency = currency
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(14, 14, 14)

    def header(self):
        # Blue top bar
        self.set_fill_color(30, 58, 138)
        self.rect(0, 0, 210, 12, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.set_xy(14, 2)
        self.cell(0, 8, self.business_name, ln=False)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, f"Page {self.page_no()} | Generated by SmartStock", align="C")
        self.set_text_color(0, 0, 0)


def generate_invoice_pdf(
    db: Session,
    sale_id: int,
    business_id: int,
) -> Path:
    """
    Generate a PDF invoice for the given sale.
    Returns the Path to the generated PDF file.
    """
    # ── Load data ─────────────────────────────────────────────────────────
    sale: Sale = get_sale(db, sale_id, business_id)

    business: Business | None = db.query(Business).filter(
        Business.id == business_id
    ).first()
    if not business:
        raise HTTPException(status_code=404, detail="Business not found")

    currency = CURRENCY_SYMBOLS.get(business.currency or "BDT", business.currency or "BDT")
    customer = sale.customer

    # Collect serials per sale_item
    item_serials: dict[int, list[str]] = {}
    for item in sale.items:
        sns = db.query(SerialNumber).filter(
            SerialNumber.sale_item_id == item.id
        ).all()
        item_serials[item.id] = [sn.serial for sn in sns]

    # ── Build PDF ─────────────────────────────────────────────────────────
    pdf = InvoicePDF(business_name=business.name, currency=currency)
    pdf.add_page()
    W = 182   # usable width (210 - 14*2)

    # ── Invoice title + number ───────────────────────────────────────────
    pdf.set_y(17)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(W, 9, "INVOICE", ln=False, align="R")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(9)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(W, 6, sale.sale_number, ln=True, align="R")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(W, 5, f"Date: {sale.sale_date.strftime('%d %b %Y')}   Status: {sale.payment_status}", ln=True, align="R")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # ── From / Bill To ───────────────────────────────────────────────────
    col = W // 2
    y_addr = pdf.get_y()

    # FROM
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.set_xy(14, y_addr)
    pdf.cell(col, 5, "FROM", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_x(14); pdf.cell(col, 5, business.name, ln=True)
    pdf.set_font("Helvetica", "", 8)
    for line in [business.address, business.phone, business.email, f"TIN: {business.tax_number}" if business.tax_number else None]:
        if line:
            pdf.set_x(14); pdf.cell(col, 4, str(line), ln=True)

    # BILL TO
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.set_xy(14 + col, y_addr)
    pdf.cell(col, 5, "BILL TO", ln=False)
    pdf.set_y(y_addr + 5)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_x(14 + col); pdf.cell(col, 5, customer.name if customer else "Walk-in Customer", ln=True)
    pdf.set_font("Helvetica", "", 8)
    if customer:
        for line in [customer.phone, customer.email, customer.address]:
            if line:
                pdf.set_x(14 + col); pdf.cell(col, 4, str(line), ln=True)

    pdf.ln(6)

    # ── Items table header ───────────────────────────────────────────────
    pdf.set_fill_color(30, 58, 138)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    col_w = [W - 72, 14, 24, 20, 14]   # Item, Qty, Unit Price, Discount, Total
    headers = ["Item", "Qty", f"Unit ({currency})", f"Disc ({currency})", f"Total ({currency})"]
    aligns = ["L", "C", "R", "R", "R"]
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 7, h, border=0, fill=True, align=aligns[i])
    pdf.ln()

    # ── Items rows ───────────────────────────────────────────────────────
    pdf.set_text_color(0, 0, 0)
    row_fill = False
    for item in sale.items:
        variant = item.variant
        product = variant.product if variant else None
        product_name = product.name if product else "—"
        variant_name = variant.name if variant else "—"
        sku = variant.sku if variant else None
        serials = item_serials.get(item.id, [])

        pdf.set_fill_color(249, 250, 251) if row_fill else pdf.set_fill_color(255, 255, 255)
        row_fill = not row_fill

        row_y = pdf.get_y()
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(col_w[0], 5, product_name[:40], fill=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(col_w[1], 5, str(item.quantity), fill=True, align="C")
        pdf.cell(col_w[2], 5, _fmt(item.unit_price), fill=True, align="R")
        pdf.cell(col_w[3], 5, _fmt(item.discount_amount) if float(item.discount_amount) > 0 else "—", fill=True, align="R")
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(col_w[4], 5, _fmt(item.total_price), fill=True, align="R", ln=True)

        # Variant + SKU sub-line
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(100, 100, 100)
        sub = variant_name + (f"  SKU: {sku}" if sku else "")
        pdf.set_fill_color(249, 250, 251) if not row_fill else pdf.set_fill_color(255, 255, 255)
        pdf.cell(col_w[0], 4, sub[:50], fill=True)
        pdf.cell(sum(col_w[1:]), 4, "", fill=True, ln=True)

        # Serial numbers
        if serials:
            pdf.set_font("Helvetica", "", 7.5)
            serial_line = "  ".join(serials)
            # Wrap if too long
            max_chars = 95
            while serial_line:
                chunk = serial_line[:max_chars]
                serial_line = serial_line[max_chars:]
                pdf.set_x(14)
                pdf.set_text_color(30, 64, 175)
                pdf.cell(W, 4, chunk, ln=True)

        pdf.set_text_color(0, 0, 0)

        # Divider
        pdf.set_draw_color(229, 231, 235)
        pdf.line(14, pdf.get_y(), 14 + W, pdf.get_y())

    pdf.ln(4)

    # ── Totals block (right-aligned) ─────────────────────────────────────
    label_x = 14 + W - 80
    val_x   = 14 + W - 30

    def total_row(label: str, value: str, bold: bool = False, color=(0, 0, 0)):
        pdf.set_font("Helvetica", "B" if bold else "", 9)
        pdf.set_text_color(*color)
        pdf.set_x(label_x)
        pdf.cell(50, 6, label, align="L")
        pdf.set_x(val_x)
        pdf.cell(30, 6, value, align="R", ln=True)
        pdf.set_text_color(0, 0, 0)

    total_row("Subtotal", f"{currency} {_fmt(sale.total_amount)}")
    if float(sale.discount_amount) > 0:
        total_row("Discount", f"- {currency} {_fmt(sale.discount_amount)}", color=(5, 150, 105))
    if sale.loyalty_points_redeemed > 0:
        loyalty_val = sale.loyalty_points_redeemed * 0.10
        total_row(f"Loyalty ({sale.loyalty_points_redeemed} pts)", f"- {currency} {_fmt(loyalty_val)}", color=(5, 150, 105))

    # Separator line
    pdf.set_draw_color(209, 213, 219)
    pdf.line(label_x, pdf.get_y(), 14 + W, pdf.get_y())
    pdf.ln(1)

    total_row("Net Payable", f"{currency} {_fmt(sale.net_payable)}", bold=True)
    total_row("Paid", f"{currency} {_fmt(sale.paid_amount)}", color=(5, 150, 105))
    if sale.due_amount > 0:
        total_row("Balance Due", f"{currency} {_fmt(sale.due_amount)}", bold=True, color=(220, 38, 38))

    pdf.ln(4)

    # ── Loyalty earned notice ────────────────────────────────────────────
    if sale.loyalty_points_earned > 0:
        pdf.set_fill_color(254, 252, 232)
        pdf.set_draw_color(253, 230, 138)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(146, 64, 14)
        pts = sale.loyalty_points_earned
        msg = f"  * {pts} loyalty point{'s' if pts != 1 else ''} earned on this purchase!"
        if customer:
            msg += f"  |  Balance: {customer.loyalty_points} pts"
        pdf.cell(W, 7, msg, border=1, fill=True, ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # ── Notes ────────────────────────────────────────────────────────────
    if sale.notes:
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(W, 5, "NOTES", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(55, 65, 81)
        pdf.multi_cell(W, 5, sale.notes)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

    # ── Thank you ────────────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(W, 7, "Thank you for your business!", align="C", ln=True)
    pdf.set_text_color(0, 0, 0)

    # ── Save ─────────────────────────────────────────────────────────────
    pdf_path = settings.PDF_DIR / f"invoice_{sale.sale_number}.pdf"
    pdf.output(str(pdf_path))
    return pdf_path
