"""phase2_no_schema_changes

Revision ID: 320dd9d2153b
Revises: a98f8e3c3e85
Create Date: 2026-09-17 21:40:59.330482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320dd9d2153b'
down_revision: Union[str, None] = 'a98f8e3c3e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
