"""phase3_categories_brands_products_variants_serials

Revision ID: 80326923b127
Revises: 320dd9d2153b
Create Date: 2026-09-17 22:10:25.340691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80326923b127'
down_revision: Union[str, None] = '320dd9d2153b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
